### ISSUE TITLE
style optimize

### ISSUE THREAD

**Issue by izayl** [charliekassel/vuejs-datepicker#50]
when using `language: zh`, the `.day-header`will be break， the last word will be droped.
using this to fixed it.
```css
span.cell.day-header {
    white-space: nowrap;
  }
```
