### ISSUE TITLE
Custom HTML for next and prev button

### ISSUE THREAD

**Issue by ngocsangyem** [charliekassel/vuejs-datepicker#839]
Is it possible to custom the HTML of the next and prev button?

**Comment by Asef00** [comment]
I didn't find any prop or option for this. But you can use the CSS content property:
```scss
.vdp-datepicker header {
  .prev:after,
  .next:after {
      content: "";
      width: 10px;
      height: 10px;
      display: inline-block;

      border-color: $primary-color;
      border-style: solid;
      border-width: 0.15em 0.15em 0 0;
      border-radius: 1px;

      position: absolute;
      top: calc(50% - 5px);
      left: calc(50% - 5px);
      margin: 0;
  }

  .prev:after {
      transform: rotate(-135deg);
  }
  .next:after {
      transform: rotate(45deg);
  }
}
```
![image](https://user-images.githubusercontent.com/50338626/177010051-5e825496-e8f6-4e84-b970-8e54269277a2.png)
